name: Java Check Version
description: Action to check if a Java projects's version strings are consistent
runs:
  using: composite
  steps:
    - run: |
        echo "BEEZ_VERSION_FILE=$(cat VERSION)" >> $GITHUB_ENV
        echo "BEEZ_GRADLE_VERSION=$(cat build.gradle | grep -oP "(?<=^version = ')[^']*")" >> $GITHUB_ENV
        [[ "$BEEZ_VERSION_FILE" == "$BEEZ_GRADLE_VERSION" ]]
      shell: bash
